# Generated by Django 2.2 on 2019-12-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac_app', '0002_auto_20191220_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
