# Generated by Django 2.2 on 2019-12-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prac_app', '0005_auto_20191220_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='likes',
            new_name='users_who_liked',
        ),
    ]
